import { BiSolidRadio } from 'react-icons/bi'
import {
    BsCircle,
    BsSquare,
    BsTriangle,
    BsEye,
    BsEyeFill,
    BsGear,
    BsGithub,
    BsCode,
    BsOctagon,
    BsCircleFill,
    BsSquareFill,
    BsTriangleFill,
    BsOctagonFill,
    BsHexagon,
    BsHexagonFill,
    BsPentagon,
    BsPentagonFill,
    BsDot,
    BsLaptop,
    BsPhone,
    BsPhoneFill,
    BsLaptopFill,
    BsGearFill,
    BsTelephone,
    BsTelephoneFill,
    BsWifi,
    BsWifiOff,
    BsCamera,
    BsCameraFill,
    BsReception0,
    BsReception2,
    BsReception3,
    BsReception4,
    BsDatabase,
    BsTv,
    BsPower,
    BsVolumeMuteFill,
    BsVolumeUpFill,
    BsVolumeDownFill,
    BsCarFrontFill,
    BsTrainFrontFill,
    BsAirplaneFill,
    BsCalculatorFill,
    BsHouse,
    BsGlobe,
    BsMapFill,
    BsBalloon,
    BsHospitalFill,
    BsMailbox,
    BsFile,
    BsXbox,
    BsBank,
    BsBluetooth,
    BsCapsulePill,
    BsCoin,
    BsCupFill,
    BsCupHotFill,
    BsDeviceHdd,
    BsDice6Fill,
    BsEmojiWink,
    BsBandaid,
    BsFuelPumpFill,
    BsPencilFill,
    BsFillPinFill,
    BsFillPostageFill,
    BsPostcardHeartFill,
    BsFillShareFill,
    BsFillStoplightsFill,
    BsFillTaxiFrontFill,
    BsFillUsbDriveFill,
    BsLampFill,
    BsLinkedin,
    BsMagnetFill,
    BsMegaphone,
    BsMouse2,
    BsPlugFill,
    BsPlusSlashMinus,
    BsRadioactive,
    BsPrinter,
    BsPuzzle,
    BsQrCode,
    BsRainbow,
    BsRecycle,
    BsRobot,
    BsDropbox,
    BsRouterFill,
    BsSend,
    BsScissors,
    BsScooter,
    BsShop,
    BsShopWindow,
    BsSim,
    BsSmartwatch,
    BsSpeedometer,
    BsSpellcheck,
    BsSoundwave,
    BsStarFill,
    BsTools,
    BsTreeFill,
    BsWind,
    BsWindow,
    BsWrenchAdjustable,
    BsWindows,
} from 'react-icons/bs'
import {
    FaAnchor,
    FaAnkh,
    FaBook,
    FaCaravan,
    FaChurch,
    FaCode,
    FaCodeBranch,
    FaCross,
    FaFacebook,
    FaFile,
    FaGem,
    FaMosque,
    FaMusic,
    FaRegCheckCircle,
    FaRegLemon,
    FaRoad,
    FaRunning,
    FaSkullCrossbones,
    FaTheaterMasks,
    FaTwitter,
    FaUser,
    FaWalking,
    FaWhatsapp,
} from 'react-icons/fa'
import {
    IoBarbell,
    IoBedOutline,
    IoBeer,
    IoBicycleOutline,
    IoBowlingBall,
    IoBriefcase,
    IoBrush,
    IoBug,
    IoBuild,
    IoBuildOutline,
    IoBulb,
    IoBus,
    IoBusiness,
    IoCalendarNumber,
    IoCardOutline,
    IoChatbox,
    IoColorFill,
    IoEarOutline,
    IoEarth,
    IoFastFoodOutline,
    IoFilm,
    IoFish,
    IoFlag,
    IoFlash,
    IoFlashlight,
    IoFlask,
    IoFlowerOutline,
    IoFootball,
    IoFootsteps,
    IoGameController,
    IoGiftOutline,
    IoGlasses,
    IoHammer,
    IoHandRight,
    IoHardwareChip,
    IoHeadset,
    IoHeart,
    IoHome,
    IoHourglassOutline,
    IoIceCreamSharp,
    IoInformation,
    IoKey,
    IoKeyOutline,
    IoKeypad,
    IoLanguage,
    IoLeafSharp,
    IoLibraryOutline,
    IoLocateSharp,
    IoLockClosed,
    IoLockOpen,
    IoLogoAmazon,
    IoLogoJavascript,
    IoLogoMicrosoft,
    IoLogoPaypal,
    IoLogoReact,
    IoLogoStackoverflow,
    IoLogoTiktok,
    IoMailOpen,
    IoMan,
    IoMedal,
    IoMic,
    IoMoon,
    IoMoonOutline,
    IoNavigate,
    IoNavigateCircle,
    IoNewspaperOutline,
    IoPaw,
    IoPint,
    IoPizza,
    IoPricetag,
    IoPrintOutline,
    IoRainy,
    IoReceipt,
    IoRestaurant,
    IoRibbon,
    IoRocketSharp,
    IoRoseSharp,
    IoSave,
    IoSaveOutline,
    IoScaleOutline,
    IoSettingsSharp,
    IoShield,
    IoShieldCheckmark,
    IoShirtOutline,
    IoSkullOutline,
    IoSnowSharp,
    IoStatsChart,
    IoStorefront,
    IoSunny,
    IoSyncCircleSharp,
    IoTelescopeSharp,
    IoTennisball,
    IoTerminal,
    IoThermometerOutline,
    IoThumbsDown,
    IoThumbsDownOutline,
    IoThumbsUp,
    IoThumbsUpOutline,
    IoToggle,
    IoTrailSign,
    IoTrain,
    IoTrash,
    IoTrophy,
    IoUmbrella,
    IoWalk,
    IoWallet,
    IoWarningOutline,
    IoWatch,
    IoWater,
    IoWine,
    IoWoman,
} from 'react-icons/io5'
import { RxLapTimer } from 'react-icons/rx'
import { TbTank, TbWorldWww } from 'react-icons/tb'
import {
    FaBasketShopping,
    FaCircleCheck,
    FaGuitar,
    FaJetFighter,
    FaMessage,
    FaPiggyBank,
    FaSailboat,
    FaShop,
    FaUserDoctor,
    FaUserGraduate,
} from 'react-icons/fa6'
import {
    MdCancel,
    MdExpandLess,
    MdExpandMore,
    MdLocalMovies,
    MdOutlineLuggage,
    MdOutlinePiano,
    MdOutlineSick,
    MdTempleBuddhist,
} from 'react-icons/md'
import { HiOfficeBuilding } from 'react-icons/hi'
import { PiOfficeChairFill } from 'react-icons/pi'
import { RiLuggageCartLine } from 'react-icons/ri'
import { LiaBirthdayCakeSolid } from 'react-icons/lia'
import {
    IoIosCafe,
    IoIosConstruct,
    IoLogoApple,
    IoLogoCss3,
    IoLogoHtml5,
    IoLogoInstagram,
    IoLogoNodejs,
    IoLogoPython,
    IoLogoSass,
    IoLogoSkype,
    IoLogoSlack,
    IoLogoYoutube,
} from 'react-icons/io'
import { GoClockFill } from 'react-icons/go'
import { Icon } from '.'
import { ImCancelCircle } from 'react-icons/im'

export const icons: Icon = {
    // Shapes
    circle: <BsCircle />,
    circle_fill: <BsCircleFill />,
    square: <BsSquare />,
    square_fill: <BsSquareFill />,
    triangle: <BsTriangle />,
    triangleFill: <BsTriangleFill />,
    octagon: <BsOctagon />,
    octagonFill: <BsOctagonFill />,
    hexagon: <BsHexagon />,
    hexagon_fill: <BsHexagonFill />,
    pentagon: <BsPentagon />,
    pentagon_fill: <BsPentagonFill />,
    dot: <BsDot />,
    cancel: <MdCancel />,
    cancel_circle: <ImCancelCircle />,
    check: <FaCircleCheck />,
    check_circle: <FaRegCheckCircle />,
    expand_less: <MdExpandLess />,
    expand_more: <MdExpandMore />,

    // Tech
    code_1: <BsCode />,
    code_2: <FaCode />,
    git_branch: <FaCodeBranch />,
    file: <FaFile />,
    github: <BsGithub />,
    laptop: <BsLaptop />,
    laptopFill: <BsLaptopFill />,
    mobile: <BsPhone />,
    mobile_fill: <BsPhoneFill />,
    telephone: <BsTelephone />,
    telephone_fill: <BsTelephoneFill />,
    wifi: <BsWifi />,
    wifi_off: <BsWifiOff />,
    camera: <BsCamera />,
    camera_fill: <BsCameraFill />,
    reception_0: <BsReception0 />,
    reception_1: <BsReception2 />,
    reception_2: <BsReception3 />,
    reception_3: <BsReception4 />,
    flashlight: <IoFlashlight />,
    flash: <IoFlash />,
    shield: <IoShield />,
    shield_check: <IoShieldCheckmark />,
    database: <BsDatabase />,
    timer: <RxLapTimer />,
    tv: <BsTv />,
    power: <BsPower />,
    volume_down: <BsVolumeDownFill />,
    volume_mute: <BsVolumeMuteFill />,
    volume_up: <BsVolumeUpFill />,
    user: <FaUser />,
    radio: <BiSolidRadio />,
    calculator: <BsCalculatorFill />,
    www: <TbWorldWww />,
    email: <BsMailbox />,
    document: <BsFile />,
    message: <FaMessage />,
    facebook: <FaFacebook />,
    whatsapp: <FaWhatsapp />,
    twitter: <FaTwitter />,
    bug: <IoBug />,
    headset: <IoHeadset />,
    hardware: <IoHardwareChip />,
    keypad: <IoKeypad />,
    js: <IoLogoJavascript />,
    nodejs: <IoLogoNodejs />,
    paypal: <IoLogoPaypal />,
    html: <IoLogoHtml5 />,
    python: <IoLogoPython />,
    microsoft: <IoLogoMicrosoft />,
    instagram: <IoLogoInstagram />,
    tiktok: <IoLogoTiktok />,
    react: <IoLogoReact />,
    sass: <IoLogoSass />,
    slack: <IoLogoSlack />,
    skype: <IoLogoSkype />,
    stack_overflow: <IoLogoStackoverflow />,
    amazon: <IoLogoAmazon />,
    css: <IoLogoCss3 />,
    apple: <IoLogoApple />,
    padlock_open: <IoLockOpen />,
    padlock_closed: <IoLockClosed />,
    youtube: <IoLogoYoutube />,
    mail_open: <IoMailOpen />,

    // Travel
    car: <BsCarFrontFill />,
    bus: <IoBus />,
    train: <BsTrainFrontFill />,
    airplain: <BsAirplaneFill />,
    caravan: <FaCaravan />,
    sail: <FaSailboat />,
    globe: <BsGlobe />,
    balloon: <BsBalloon />,
    map: <BsMapFill />,
    road: <FaRoad />,
    luggage_1: <RiLuggageCartLine />,
    luggage_2: <MdOutlineLuggage />,
    earth: <IoEarth />,
    flag: <IoFlag />,
    fish: <IoFish />,
    compass: <IoNavigateCircle />,

    // Places
    house: <BsHouse />,
    hospital: <BsHospitalFill />,
    office: <HiOfficeBuilding />,
    office_chair: <PiOfficeChairFill />,
    leaf: <IoLeafSharp />,
    library: <IoLibraryOutline />,
    location: <IoLocateSharp />,
    doctor: <FaUserDoctor />,
    cross: <FaCross />,
    skull: <FaSkullCrossbones />,
    mosque: <FaMosque />,
    church: <FaChurch />,
    anchor: <FaAnchor />,
    ankh: <FaAnkh />,
    piggy_bank: <FaPiggyBank />,
    buddha: <MdTempleBuddhist />,
    gem: <FaGem />,
    fighter_jet: <FaJetFighter />,
    tank: <TbTank />,
    coffee: <IoIosCafe />,

    // Body
    eye: <BsEye />,
    eye_fill: <BsEyeFill />,
    gear: <BsGear />,
    gear_fill: <BsGearFill />,
    ear: <IoEarOutline />,
    foot_steps: <IoFootsteps />,
    hand: <IoHandRight />,
    heart: <IoHeart />,

    // Activities
    xbox: <BsXbox />,
    running: <FaRunning />,
    walking: <FaWalking />,
    shopping: <FaShop />,
    shopping_basket: <FaBasketShopping />,
    book: <FaBook />,
    music: <FaMusic />,
    guitar: <FaGuitar />,
    piano: <MdOutlinePiano />,
    training: <IoBarbell />,
    sleep: <IoBedOutline />,
    beer: <IoBeer />,
    bike: <IoBicycleOutline />,
    bowling: <IoBowlingBall />,
    paint_brush: <IoBrush />,
    business: <IoBusiness />,
    pay: <IoCardOutline />,
    chat: <IoChatbox />,
    colour: <IoColorFill />,
    food: <IoFastFoodOutline />,
    film: <IoFilm />,
    flask: <IoFlask />,
    flower: <IoFlowerOutline />,
    football: <IoFootball />,
    controller: <IoGameController />,
    glasses: <IoGlasses />,
    hammer: <IoHammer />,
    ice_cream: <IoIceCreamSharp />,
    info: <IoInformation />,
    language: <IoLanguage />,
    newspaper: <IoNewspaperOutline />,
    movie: <MdLocalMovies />,

    // Time
    moon_outline: <IoMoonOutline />,
    moon: <IoMoon />,
    sun: <IoSunny />,
    calendar: <IoCalendarNumber />,
    hourglass: <IoHourglassOutline />,

    // Events
    birthday: <LiaBirthdayCakeSolid />,
    sick: <MdOutlineSick />,
    graduation: <FaUserGraduate />,
    education: <FaUserGraduate />,
    work: <IoBriefcase />,
    build: <IoBuild />,
    build_outline: <IoBuildOutline />,
    bulb: <IoBulb />,
    gift: <IoGiftOutline />,
    home: <IoHome />,
    key: <IoKey />,
    key_outline: <IoKeyOutline />,

    // Misc
    medal: <IoMedal />,
    mic: <IoMic />,
    navigate: <IoNavigate />,
    paw: <IoPaw />,
    pizza: <IoPizza />,
    pint: <IoPint />,
    pricetag: <IoPricetag />,
    print: <IoPrintOutline />,
    rain: <IoRainy />,
    receipt: <IoReceipt />,
    restaurant: <IoRestaurant />,
    ribbon: <IoRibbon />,
    save: <IoSave />,
    save_outline: <IoSaveOutline />,
    rocket: <IoRocketSharp />,
    rose: <IoRoseSharp />,
    scale: <IoScaleOutline />,
    settings: <IoSettingsSharp />,
    shirt: <IoShirtOutline />,
    skull_outline: <IoSkullOutline />,
    snow: <IoSnowSharp />,
    charts: <IoStatsChart />,
    store: <IoStorefront />,
    sync: <IoSyncCircleSharp />,
    telescope: <IoTelescopeSharp />,
    tennis: <IoTennisball />,
    terminal: <IoTerminal />,
    thermometer: <IoThermometerOutline />,
    theatre: <FaTheaterMasks />,
    construction: <IoIosConstruct />,
    lemon: <FaRegLemon />,
    thumbs_down: <IoThumbsDown />,
    thumbs_down_outline: <IoThumbsDownOutline />,
    thumbs_up: <IoThumbsUp />,
    thumbs_up_outline: <IoThumbsUpOutline />,
    toggle: <IoToggle />,
    trail: <IoTrailSign />,
    train_2: <IoTrain />,
    trash: <IoTrash />,
    trophy: <IoTrophy />,
    umbrella: <IoUmbrella />,
    wallet: <IoWallet />,
    warning: <IoWarningOutline />,
    walk: <IoWalk />,
    water: <IoWater />,
    wine: <IoWine />,
    watch: <IoWatch />,
    men: <IoMan />,
    women: <IoWoman />,
    clock: <GoClockFill />,
    bank: <BsBank />,
    bluetooth: <BsBluetooth />,
    medication: <BsCapsulePill />,
    coin: <BsCoin />,
    cup: <BsCupFill />,
    mug: <BsCupHotFill />,
    hdd: <BsDeviceHdd />,
    dice: <BsDice6Fill />,
    emoji_wink: <BsEmojiWink />,
    band_aid: <BsBandaid />,
    fuel: <BsFuelPumpFill />,
    pencil: <BsPencilFill />,
    pin: <BsFillPinFill />,
    stamp: <BsFillPostageFill />,
    postcard: <BsPostcardHeartFill />,
    share: <BsFillShareFill />,
    traffic: <BsFillStoplightsFill />,
    taxi: <BsFillTaxiFrontFill />,
    usb_drive: <BsFillUsbDriveFill />,
    lamp: <BsLampFill />,
    linkedin: <BsLinkedin />,
    magnet: <BsMagnetFill />,
    mega_phone: <BsMegaphone />,
    mouse: <BsMouse2 />,
    plug: <BsPlugFill />,
    plus_minus: <BsPlusSlashMinus />,
    radio_active: <BsRadioactive />,
    printer: <BsPrinter />,
    puzzle: <BsPuzzle />,
    qr_code: <BsQrCode />,
    rainbow: <BsRainbow />,
    recycle: <BsRecycle />,
    robot: <BsRobot />,
    drop_box: <BsDropbox />,
    router: <BsRouterFill />,
    send: <BsSend />,
    scissors: <BsScissors />,
    scooter: <BsScooter />,
    shop_2: <BsShop />,
    shop_3: <BsShopWindow />,
    sim: <BsSim />,
    smart_watch: <BsSmartwatch />,
    speedometer: <BsSpeedometer />,
    abc: <BsSpellcheck />,
    sound_wave: <BsSoundwave />,
    star: <BsStarFill />,
    tools: <BsTools />,
    tree: <BsTreeFill />,
    wind: <BsWind />,
    window: <BsWindow />,
    wrench: <BsWrenchAdjustable />,
    windows: <BsWindows />,
}
