module.exports = {
    roots: ['<rootDir>/src', '<rootDir>/common'],
    transform: { '^.+\\.tsx?$': 'ts-jest' },
    testEnvironment: 'jsdom',
    testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
    resolver: '<rootDir>/jest.resolver.cjs',
    setupFiles: ['<rootDir>/jest.polyfills.cjs'],
    moduleNameMapper: {
        '^@app/(.*)$': '<rootDir>/src/app/$1',
        '^@portfolio/(.*)$': '<rootDir>/src/portfolio/$1',
        '^@projects/(.*)$': '<rootDir>/src/projects/$1',
        '^@common-types$': '<rootDir>/common/types',
        '^@common-types/(.*)$': '<rootDir>/common/types/$1',
        '^@common-ux$': '<rootDir>/common/ux',
        '^@common-ux/(.*)$': '<rootDir>/common/ux/$1',
        '^@common-utils$': '<rootDir>/common/utils',
        '^@common-utils/(.*)$': '<rootDir>/common/utils/$1',
        '^@shared-styles/(.*)$': '<rootDir>/src/shared/styles/$1',
        '^@shared-queries/(.*)$': '<rootDir>/src/shared/queries/$1',
        '^@shared-assets/(.*)$': '<rootDir>/src/shared/assets/$1',
        '^@shared-components/(.*)$': '<rootDir>/src/shared/components/$1',
        '^@shared-context/(.*)$': '<rootDir>/src/shared/context/$1',
        '^@public/(.*)$': '<rootDir>/public/$1',
        '^react-syntax-highlighter/dist/esm/styles/(.*)$': '<rootDir>/file-mock.js',
        '^react-syntax-highlighter$': '<rootDir>/__mocks__/react-syntax-highlighter.js',
        '\\.s?css$': 'identity-obj-proxy',
        '\\.svg$': '<rootDir>/file-mock.js',
        '\\.pdf$': '<rootDir>/file-mock.js',
        '\\.png$': '<rootDir>/file-mock.js',
        '\\.jpe?g$': '<rootDir>/file-mock.js',
    },
    setupFilesAfterEnv: [
        //"@testing-library/react/cleanup-after-each",
        //"@testing-library/jest-dom/extend-expect",
        '<rootDir>/src/setupTests.ts',
    ],
}
