export { Activities } from './Activities/Activities'
export { Admin } from './Admin/Admin'
export { Categories } from './Categories/Categories'
export { EmailVerification } from './EmailVerification/EmailVerification'
export { Events } from './Events/Events'
export { Home } from './Home/Home'
export { Login } from './Login/Login'
export { Logout } from './Logout/Logout'
export { AddRecords } from './Record/AddRecords/AddRecords'
export { ViewRecord } from './Record/ViewRecord'
export { UpdateRecords } from './Record/UpdateRecords'
export { Register } from './Register/Register'
export { Remote } from './Remote/Remote'
export { Stats } from './Stats/Stats'
export { Tasks } from './Tasks/Tasks'
export { User } from './User/User'
export { AppRoutes, AppRoutesList } from './App.routes'
export type { AppRoute } from './App.routes'
