import { ReactNode } from 'react'
import { BiSolidRadio, BiSolidTimer } from 'react-icons/bi'
import {
    BsCircle,
    BsSquare,
    BsTriangle,
    BsEye,
    BsEyeFill,
    BsGear,
    BsGithub,
    BsCode,
    BsOctagon,
    BsCircleFill,
    BsSquareFill,
    BsTriangleFill,
    BsOctagonFill,
    BsHexagon,
    BsHexagonFill,
    BsPentagon,
    BsPentagonFill,
    BsDot,
    BsLaptop,
    BsPhone,
    BsPhoneFill,
    BsLaptopFill,
    BsGearFill,
    BsTelephone,
    BsTelephoneFill,
    BsWifi,
    BsWifiOff,
    BsCamera,
    BsCameraFill,
    BsReception0,
    BsReception2,
    BsReception3,
    BsReception4,
    BsDatabase,
    BsTv,
    BsPower,
    BsVolumeDown,
    BsVolumeMute,
    BsVolumeMuteFill,
    BsVolumeUpFill,
    BsVolumeDownFill,
    BsCarFrontFill,
    BsTrainFrontFill,
    BsAirplaneFill,
    BsCalculatorFill,
    BsHouse,
    BsGlobe,
    BsMapFill,
    BsBalloon,
    BsHospitalFill,
    BsMailbox,
    BsFile,
    BsXbox,
} from 'react-icons/bs'
import {
    FaCaravan,
    FaCode,
    FaCodeBranch,
    FaFile,
    FaRoad,
    FaRunning,
    FaUser,
    FaWalking,
} from 'react-icons/fa'
import {
    IoFlash,
    IoFlashlight,
    IoShield,
    IoShieldCheckmark,
} from 'react-icons/io5'
import { RxLapTimer } from 'react-icons/rx'
import { TbWorldWww } from 'react-icons/tb'
import { FaBasketShopping, FaSailboat, FaShop } from 'react-icons/fa6'
import { HiOfficeBuilding } from 'react-icons/hi'
import { FacebookIcon, PinterestIcon, TwitterIcon } from 'react-share'
import { PiOfficeChairFill } from 'react-icons/pi'

export const icons: Record<string, ReactNode> = {
    // Shapes
    circle: <BsCircle />,
    circle_fill: <BsCircleFill />,
    square: <BsSquare />,
    square_fill: <BsSquareFill />,
    triangle: <BsTriangle />,
    triangleFill: <BsTriangleFill />,
    octagon: <BsOctagon />,
    octagonFill: <BsOctagonFill />,
    hexagon: <BsHexagon />,
    hexagon_fill: <BsHexagonFill />,
    pentagon: <BsPentagon />,
    pentagon_fill: <BsPentagonFill />,
    dot: <BsDot />,

    // Tech
    code_1: <BsCode />,
    code_2: <FaCode />,
    git_branch: <FaCodeBranch />,
    file: <FaFile />,
    github: <BsGithub />,
    laptop: <BsLaptop />,
    laptopFill: <BsLaptopFill />,
    mobile: <BsPhone />,
    mobile_fill: <BsPhoneFill />,
    telephone: <BsTelephone />,
    telephone_fill: <BsTelephoneFill />,
    wifi: <BsWifi />,
    wifi_off: <BsWifiOff />,
    camera: <BsCamera />,
    camera_fill: <BsCameraFill />,
    reception_0: <BsReception0 />,
    reception_1: <BsReception2 />,
    reception_2: <BsReception3 />,
    reception_3: <BsReception4 />,
    flashlight: <IoFlashlight />,
    flash: <IoFlash />,
    shield: <IoShield />,
    shield_check: <IoShieldCheckmark />,
    database: <BsDatabase />,
    timer: <RxLapTimer />,
    tv: <BsTv />,
    power: <BsPower />,
    volume_down: <BsVolumeDownFill />,
    volume_mute: <BsVolumeMuteFill />,
    volume_up: <BsVolumeUpFill />,
    user: <FaUser />,
    radio: <BiSolidRadio />,
    calculator: <BsCalculatorFill />,
    www: <TbWorldWww />,
    email: <BsMailbox />,
    document: <BsFile />,

    // Travel
    car: <BsCarFrontFill />,
    train: <BsTrainFrontFill />,
    airplain: <BsAirplaneFill />,
    caravan: <FaCaravan />,
    sail: <FaSailboat />,
    globe: <BsGlobe />,
    balloon: <BsBalloon />,
    map: <BsMapFill />,
    road: <FaRoad />,

    // Places
    house: <BsHouse />,
    hospital: <BsHospitalFill />,
    office: <HiOfficeBuilding />,
    office_chair: <PiOfficeChairFill />,

    // Body
    eye: <BsEye />,
    eye_fill: <BsEyeFill />,
    gear: <BsGear />,
    gear_fill: <BsGearFill />,

    // Activities
    xbox: <BsXbox />,
    running: <FaRunning />,
    walking: <FaWalking />,
    shopping: <FaShop />,
    shopping_basket: <FaBasketShopping />,
}
